[package]
name = "cooklang_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "cooklang_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34"
cooklang = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
